In [2]:
import pandas as pd
import glob

# Find all phillips_lots_*.csv files
csv_files = glob.glob('phillips_lots_*.csv')
print(f"Found {len(csv_files)} files to concatenate:")
for f in sorted(csv_files):
    print(f"  - {f}")

# Read and concatenate all files
all_dfs = []
for file in sorted(csv_files):
    df = pd.read_csv(file)
    all_dfs.append(df)
    print(f" Loaded {file}: {len(df)} rows")

# Concatenate all DataFrames
if all_dfs:
    combined_df = pd.concat(all_dfs, ignore_index=True)
    
    output_file = 'phillips_all_lots.csv'
    combined_df.to_csv(output_file, index=False, encoding='utf-8-sig')
    print(f"\n Saved combined file: {output_file}")
    print(f" Total rows: {len(combined_df)}")

Found 35 files to concatenate:
  - phillips_lots_10.csv
  - phillips_lots_100.csv
  - phillips_lots_110.csv
  - phillips_lots_120.csv
  - phillips_lots_130.csv
  - phillips_lots_140.csv
  - phillips_lots_150.csv
  - phillips_lots_160.csv
  - phillips_lots_170.csv
  - phillips_lots_180.csv
  - phillips_lots_190.csv
  - phillips_lots_20.csv
  - phillips_lots_200.csv
  - phillips_lots_210.csv
  - phillips_lots_220.csv
  - phillips_lots_230.csv
  - phillips_lots_240.csv
  - phillips_lots_250.csv
  - phillips_lots_260.csv
  - phillips_lots_270.csv
  - phillips_lots_280.csv
  - phillips_lots_290.csv
  - phillips_lots_30.csv
  - phillips_lots_300.csv
  - phillips_lots_310.csv
  - phillips_lots_320.csv
  - phillips_lots_330.csv
  - phillips_lots_340.csv
  - phillips_lots_350.csv
  - phillips_lots_40.csv
  - phillips_lots_50.csv
  - phillips_lots_60.csv
  - phillips_lots_70.csv
  - phillips_lots_80.csv
  - phillips_lots_90.csv
 Loaded phillips_lots_10.csv: 1238 rows
 Loaded phillips_lots_100.csv: 635 rows
 Loaded phillips_lots_110.csv: 814 rows
 Loaded phillips_lots_120.csv: 376 rows
 Loaded phillips_lots_130.csv: 770 rows
 Loaded phillips_lots_140.csv: 597 rows
 Loaded phillips_lots_150.csv: 725 rows
 Loaded phillips_lots_160.csv: 626 rows
 Loaded phillips_lots_170.csv: 567 rows
 Loaded phillips_lots_180.csv: 982 rows
 Loaded phillips_lots_190.csv: 567 rows
 Loaded phillips_lots_20.csv: 844 rows
 Loaded phillips_lots_200.csv: 956 rows
 Loaded phillips_lots_210.csv: 652 rows
 Loaded phillips_lots_220.csv: 1000 rows
 Loaded phillips_lots_230.csv: 838 rows
 Loaded phillips_lots_240.csv: 917 rows
 Loaded phillips_lots_250.csv: 909 rows
 Loaded phillips_lots_260.csv: 1277 rows
 Loaded phillips_lots_270.csv: 820 rows
 Loaded phillips_lots_280.csv: 1153 rows
 Loaded phillips_lots_290.csv: 1088 rows
 Loaded phillips_lots_30.csv: 1205 rows
 Loaded phillips_lots_300.csv: 1329 rows
 Loaded phillips_lots_310.csv: 1334 rows
 Loaded phillips_lots_320.csv: 1502 rows
 Loaded phillips_lots_330.csv: 1177 rows
 Loaded phillips_lots_340.csv: 1345 rows
 Loaded phillips_lots_350.csv: 1032 rows
 Loaded phillips_lots_40.csv: 1118 rows
 Loaded phillips_lots_50.csv: 750 rows
 Loaded phillips_lots_60.csv: 1098 rows
 Loaded phillips_lots_70.csv: 774 rows
 Loaded phillips_lots_80.csv: 550 rows
 Loaded phillips_lots_90.csv: 896 rows

 Saved combined file: phillips_all_lots.csv
 Total rows: 32461

In [10]:
import re

df_cleaned = df[df['price'].notna()].reset_index(drop=True)

def split_estimate(val):
    text = str(val).strip()
    
    if not text or text == 'nan':
        return pd.Series([None, None])
    

    matches = re.findall(r'\d{1,3}(?:,\d{3})*(?:\.\d+)?|\d+(?:\.\d+)?', text)
    
    clean_nums = []
    for m in matches:
        try:
            num = float(m.replace(',', ''))
            clean_nums.append(num)
        except ValueError:
            continue
    
    if len(clean_nums) < 2:
        return pd.Series([None, None])
    
    return pd.Series([clean_nums[0], clean_nums[1]])

df_cleaned[['estimate_low', 'estimate_high']] = df_cleaned['estimate'].apply(split_estimate)

In [11]:
df_cleaned

,auction_title,auction_url,auction_date,lot_url,lot_number,artist,title,estimate,price,currency,image_url,estimate_low,estimate_high
0,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/poppy-jones/23...,230324.0,Poppy Jones,Dreamers II,"£10,000 - £15,000",24510.0,£,https://assets.phillips.com/auctions/UK010326/...,10000.0,15000.0
1,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/joseph-yaeger/...,231753.0,Joseph Yaeger,"Thanks, Democritus","£20,000 - £30,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0
2,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/sarah-cunningh...,230396.0,Sarah Cunningham,Mother Wound,"£35,000 - £55,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,35000.0,55000.0
3,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/lucas-arruda/2...,230235.0,Lucas Arruda,Untitled 14,"£80,000 - £120,000",109650.0,£,https://assets.phillips.com/auctions/UK010326/...,80000.0,120000.0
4,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/yu-nishimura/2...,231482.0,Yu Nishimura,On the Table,"£20,000 - £30,000",38700.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24812,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-sérusier/...,193320.0,Paul Sérusier,La Cueillette des pommes,"$1,500,000 - $2,000,000",1391000.0,$,https://assets.phillips.com/auctions/NY011123/...,1500000.0,2000000.0
24813,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/félix-vallotto...,193324.0,Félix Vallotton,Papotage,"$300,000 - $500,000",330200.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0
24814,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-gauguin/1...,193312.0,Paul Gauguin,Masque de Meyer de Haan,"$60,000 - $80,000",66040.0,$,https://assets.phillips.com/auctions/NY011123/...,60000.0,80000.0
24815,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/robert-ryman/1...,193335.0,Robert Ryman,"Untitled, Prototype","$300,000 - $500,000",254000.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0
24816,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/sam-francis/19...,193329.0,Sam Francis,"Purple, Orange & Green","$200,000 - $300,000",482600.0,$,https://assets.phillips.com/auctions/NY011123/...,200000.0,300000.0

In [12]:
def get_currency_code(row):
    curr = row['currency']
    url = str(row['auction_url'])
    
    # Если валюта уже определена как фунт
    if curr == '£':
        return 'GBP'
    
    # Если доллар ($), проверяем локацию
    if curr == '$' or pd.isna(curr):
        if '/HK' in url or 'HONG KONG' in str(row['auction_title']).upper():
            return 'HKD'
        else:
            # По умолчанию считаем USD 
            return 'USD'
            
    return 'USD' 

# Применяем функцию
df_cleaned['currency_code'] = df_cleaned.apply(get_currency_code, axis=1)

# Проверка распределения
print("Распределение валют после обработки:")
print(df_cleaned['currency_code'].value_counts())

Распределение валют после обработки:
currency_code
USD    11566
GBP    10016
HKD     3235
Name: count, dtype: int64

In [13]:
df_cleaned

,auction_title,auction_url,auction_date,lot_url,lot_number,artist,title,estimate,price,currency,image_url,estimate_low,estimate_high,currency_code
0,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/poppy-jones/23...,230324.0,Poppy Jones,Dreamers II,"£10,000 - £15,000",24510.0,£,https://assets.phillips.com/auctions/UK010326/...,10000.0,15000.0,GBP
1,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/joseph-yaeger/...,231753.0,Joseph Yaeger,"Thanks, Democritus","£20,000 - £30,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0,GBP
2,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/sarah-cunningh...,230396.0,Sarah Cunningham,Mother Wound,"£35,000 - £55,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,35000.0,55000.0,GBP
3,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/lucas-arruda/2...,230235.0,Lucas Arruda,Untitled 14,"£80,000 - £120,000",109650.0,£,https://assets.phillips.com/auctions/UK010326/...,80000.0,120000.0,GBP
4,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/yu-nishimura/2...,231482.0,Yu Nishimura,On the Table,"£20,000 - £30,000",38700.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24812,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-sérusier/...,193320.0,Paul Sérusier,La Cueillette des pommes,"$1,500,000 - $2,000,000",1391000.0,$,https://assets.phillips.com/auctions/NY011123/...,1500000.0,2000000.0,USD
24813,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/félix-vallotto...,193324.0,Félix Vallotton,Papotage,"$300,000 - $500,000",330200.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0,USD
24814,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-gauguin/1...,193312.0,Paul Gauguin,Masque de Meyer de Haan,"$60,000 - $80,000",66040.0,$,https://assets.phillips.com/auctions/NY011123/...,60000.0,80000.0,USD
24815,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/robert-ryman/1...,193335.0,Robert Ryman,"Untitled, Prototype","$300,000 - $500,000",254000.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0,USD
24816,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/sam-francis/19...,193329.0,Sam Francis,"Purple, Orange & Green","$200,000 - $300,000",482600.0,$,https://assets.phillips.com/auctions/NY011123/...,200000.0,300000.0,USD

In [14]:
pip install python-dateutil

Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.13/site-packages (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pandas as pd
from dateutil import parser as date_parser

def clean_date(val):
    if pd.isna(val) or str(val).strip() == '' or str(val).strip().lower() == 'unknown':
        return pd.NaT
    
    try:
        parsed_date = date_parser.parse(str(val), fuzzy=True)
        return parsed_date.strftime('%Y-%m-%d')
    except Exception:
        # Если не удалось распарсить
        return pd.NaT

# Применяем функцию
df_cleaned['auction_date_clean'] = df_cleaned['auction_date'].apply(clean_date)

# Преобразуем в тип datetime (для удобной сортировки и фильтрации)
df_cleaned['auction_date_clean'] = pd.to_datetime(df_cleaned['auction_date_clean'], errors='coerce')

/opt/anaconda3/lib/python3.13/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname ET identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
/opt/anaconda3/lib/python3.13/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname HKT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
/opt/anaconda3/lib/python3.13/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname BST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [16]:
df_cleaned

,auction_title,auction_url,auction_date,lot_url,lot_number,artist,title,estimate,price,currency,image_url,estimate_low,estimate_high,currency_code,auction_date_clean
0,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/poppy-jones/23...,230324.0,Poppy Jones,Dreamers II,"£10,000 - £15,000",24510.0,£,https://assets.phillips.com/auctions/UK010326/...,10000.0,15000.0,GBP,2026-03-07
1,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/joseph-yaeger/...,231753.0,Joseph Yaeger,"Thanks, Democritus","£20,000 - £30,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0,GBP,2026-03-07
2,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/sarah-cunningh...,230396.0,Sarah Cunningham,Mother Wound,"£35,000 - £55,000",49020.0,£,https://assets.phillips.com/auctions/UK010326/...,35000.0,55000.0,GBP,2026-03-07
3,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/lucas-arruda/2...,230235.0,Lucas Arruda,Untitled 14,"£80,000 - £120,000",109650.0,£,https://assets.phillips.com/auctions/UK010326/...,80000.0,120000.0,GBP,2026-03-07
4,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/yu-nishimura/2...,231482.0,Yu Nishimura,On the Table,"£20,000 - £30,000",38700.0,£,https://assets.phillips.com/auctions/UK010326/...,20000.0,30000.0,GBP,2026-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24812,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-sérusier/...,193320.0,Paul Sérusier,La Cueillette des pommes,"$1,500,000 - $2,000,000",1391000.0,$,https://assets.phillips.com/auctions/NY011123/...,1500000.0,2000000.0,USD,2023-11-14
24813,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/félix-vallotto...,193324.0,Félix Vallotton,Papotage,"$300,000 - $500,000",330200.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0,USD,2023-11-14
24814,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-gauguin/1...,193312.0,Paul Gauguin,Masque de Meyer de Haan,"$60,000 - $80,000",66040.0,$,https://assets.phillips.com/auctions/NY011123/...,60000.0,80000.0,USD,2023-11-14
24815,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/robert-ryman/1...,193335.0,Robert Ryman,"Untitled, Prototype","$300,000 - $500,000",254000.0,$,https://assets.phillips.com/auctions/NY011123/...,300000.0,500000.0,USD,2023-11-14
24816,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/sam-francis/19...,193329.0,Sam Francis,"Purple, Orange & Green","$200,000 - $300,000",482600.0,$,https://assets.phillips.com/auctions/NY011123/...,200000.0,300000.0,USD,2023-11-14

In [18]:
pip install forex-python

Collecting forex-python
  Downloading forex_python-1.9.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: requests>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from forex-python) (2.32.5)
Collecting simplejson>=3.0 (from forex-python)
  Downloading simplejson-3.20.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0->forex-python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0->forex-python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0->forex-python) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.0->forex-python) (2026.2.25)
Downloading forex_python-1.9.2-py3-none-any.whl (9.5 kB)
Downloading simplejson-3.20.2-cp313-cp313-macosx_11_0_arm64.whl (75 kB)
Installing collected packages: simplejson, forex-python
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [forex-python]
Successfully installed forex-python-1.9.2 simplejson-3.20.2
Note: you may need to restart the kernel to use updated packages.

In [28]:
df_cleaned

,auction_title,auction_url,auction_date,lot_url,lot_number,artist,title,estimate,price,currency,...,estimate_low,estimate_high,currency_code,auction_date_clean,date_obj,year,month,price_usd_raw,price_usd_2026,applied_rate
0,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/poppy-jones/23...,230324.0,Poppy Jones,Dreamers II,"£10,000 - £15,000",24510.0,£,...,10000.0,15000.0,GBP,2026-03-07,2026-03-07,2026,3,3.255092e+04,3.255092e+04,1.328067
1,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/joseph-yaeger/...,231753.0,Joseph Yaeger,"Thanks, Democritus","£20,000 - £30,000",49020.0,£,...,20000.0,30000.0,GBP,2026-03-07,2026-03-07,2026,3,6.510184e+04,6.510184e+04,1.328067
2,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/sarah-cunningh...,230396.0,Sarah Cunningham,Mother Wound,"£35,000 - £55,000",49020.0,£,...,35000.0,55000.0,GBP,2026-03-07,2026-03-07,2026,3,6.510184e+04,6.510184e+04,1.328067
3,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/lucas-arruda/2...,230235.0,Lucas Arruda,Untitled 14,"£80,000 - £120,000",109650.0,£,...,80000.0,120000.0,GBP,2026-03-07,2026-03-07,2026,3,1.456225e+05,1.456225e+05,1.328067
4,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/yu-nishimura/2...,231482.0,Yu Nishimura,On the Table,"£20,000 - £30,000",38700.0,£,...,20000.0,30000.0,GBP,2026-03-07,2026-03-07,2026,3,5.139619e+04,5.139619e+04,1.328067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24812,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-sérusier/...,193320.0,Paul Sérusier,La Cueillette des pommes,"$1,500,000 - $2,000,000",1391000.0,$,...,1500000.0,2000000.0,USD,2023-11-14,2023-11-14,2023,11,1.391000e+06,1.542227e+06,1.000000
24813,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/félix-vallotto...,193324.0,Félix Vallotton,Papotage,"$300,000 - $500,000",330200.0,$,...,300000.0,500000.0,USD,2023-11-14,2023-11-14,2023,11,3.302000e+05,3.660986e+05,1.000000
24814,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-gauguin/1...,193312.0,Paul Gauguin,Masque de Meyer de Haan,"$60,000 - $80,000",66040.0,$,...,60000.0,80000.0,USD,2023-11-14,2023-11-14,2023,11,6.604000e+04,7.321973e+04,1.000000
24815,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/robert-ryman/1...,193335.0,Robert Ryman,"Untitled, Prototype","$300,000 - $500,000",254000.0,$,...,300000.0,500000.0,USD,2023-11-14,2023-11-14,2023,11,2.540000e+05,2.816143e+05,1.000000
24816,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/sam-francis/19...,193329.0,Sam Francis,"Purple, Orange & Green","$200,000 - $300,000",482600.0,$,...,200000.0,300000.0,USD,2023-11-14,2023-11-14,2023,11,4.826000e+05,5.350672e+05,1.000000

In [30]:
import pandas as pd
from datetime import datetime
from forex_python.converter import CurrencyRates

# Инициализация конвертера
c = CurrencyRates()

df_cleaned['date_obj'] = pd.to_datetime(df_cleaned['auction_date_clean'], errors='coerce')
df_cleaned['year'] = df_cleaned['date_obj'].dt.year
df_cleaned['month'] = df_cleaned['date_obj'].dt.month

#Определяем уникальные пары (Валюта, Год, Месяц), которые нужно запросить
unique_combinations = df_cleaned.dropna(subset=['currency_code', 'year', 'month'])[['currency_code', 'year', 'month']].drop_duplicates()

exchange_rates_map = {}

print(f"Получение курсов валют для {len(unique_combinations)} уникальных комбинаций...")

for _, row in unique_combinations.iterrows():
    curr = row['currency_code']
    year = int(row['year'])
    month = int(row['month'])
    
    if curr == 'USD':
        exchange_rates_map[(curr, year, month)] = 1.0
        continue
    
    try:
        date_val = datetime(year, month, 28)
        rate = c.get_rate(curr, 'USD', date_val)
        exchange_rates_map[(curr, year, month)] = rate
    except Exception:
        try:
            rate = c.get_rate(curr, 'USD')
            exchange_rates_map[(curr, year, month)] = rate
        except:
            exchange_rates_map[(curr, year, month)] = None

#Функция для быстрого расчета
def calculate_final_values(row):
    price = row['price']
    curr = row['currency_code']
    year = row['year']
    month = row['month']
    
    if pd.isna(price) or price == 0 or pd.isna(curr):
        return pd.Series([None, None, None])
    
    rate = exchange_rates_map.get((curr, year, month))
    
    if rate is None:
        return pd.Series([None, None, None])
    
    # Конвертация
    price_usd_raw = price * rate
    
    # Инфляция
    if pd.notna(year):
        years_diff = 2026 - year
        if years_diff > 0:
            price_usd_2026 = price_usd_raw * ((1.035) ** years_diff)
        else:
            price_usd_2026 = price_usd_raw
    else:
        price_usd_2026 = price_usd_raw
        
    return pd.Series([price_usd_raw, price_usd_2026, rate])

#Применяем функцию к df_cleaned
results = df_cleaned.apply(calculate_final_values, axis=1)

df_cleaned['price_usd_raw'] = results[0]
df_cleaned['price_usd_2026'] = results[1]
df_cleaned['applied_rate'] = results[2]

#То же самое для эстимейтов
def calc_estimate(row, col_name):
    val = row[col_name]
    curr = row['currency_code']
    year = row['year']
    month = row['month']
    
    if pd.isna(val) or val == 0 or pd.isna(curr):
        return None
    
    rate = exchange_rates_map.get((curr, year, month))
    if rate is None: return None
    
    raw = val * rate
    if pd.notna(year) and (2026 - year) > 0:
        return raw * ((1.035) ** (2026 - year))
    return raw

if 'estimate_low' in df_cleaned.columns:
    df_cleaned['estimate_low_usd_2026'] = df_cleaned.apply(lambda r: calc_estimate(r, 'estimate_low'), axis=1)

if 'estimate_high' in df_cleaned.columns:
    df_cleaned['estimate_high_usd_2026'] = df_cleaned.apply(lambda r: calc_estimate(r, 'estimate_high'), axis=1)

print("Готово!")
print(df_cleaned[['price', 'currency_code', 'price_usd_raw', 'price_usd_2026']].head(10))

Получение курсов валют для 168 уникальных комбинаций...
Курсы получены. Начинаем расчеты...
✅ Готово!
      price currency_code  price_usd_raw  price_usd_2026
0   24510.0           GBP    32550.92217     32550.92217
1   49020.0           GBP    65101.84434     65101.84434
2   49020.0           GBP    65101.84434     65101.84434
3  109650.0           GBP   145622.54655    145622.54655
4   38700.0           GBP    51396.19290     51396.19290

In [31]:
df_cleaned

,auction_title,auction_url,auction_date,lot_url,lot_number,artist,title,estimate,price,currency,...,currency_code,auction_date_clean,date_obj,year,month,price_usd_raw,price_usd_2026,applied_rate,estimate_low_usd_2026,estimate_high_usd_2026
0,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/poppy-jones/23...,230324.0,Poppy Jones,Dreamers II,"£10,000 - £15,000",24510.0,£,...,GBP,2026-03-07,2026-03-07,2026,3,3.255092e+04,3.255092e+04,1.328067,1.328067e+04,1.992101e+04
1,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/joseph-yaeger/...,231753.0,Joseph Yaeger,"Thanks, Democritus","£20,000 - £30,000",49020.0,£,...,GBP,2026-03-07,2026-03-07,2026,3,6.510184e+04,6.510184e+04,1.328067,2.656134e+04,3.984201e+04
2,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/sarah-cunningh...,230396.0,Sarah Cunningham,Mother Wound,"£35,000 - £55,000",49020.0,£,...,GBP,2026-03-07,2026-03-07,2026,3,6.510184e+04,6.510184e+04,1.328067,4.648235e+04,7.304369e+04
3,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/lucas-arruda/2...,230235.0,Lucas Arruda,Untitled 14,"£80,000 - £120,000",109650.0,£,...,GBP,2026-03-07,2026-03-07,2026,3,1.456225e+05,1.456225e+05,1.328067,1.062454e+05,1.593680e+05
4,MODERN & CONTEMPORARY ART,https://www.phillips.com/auction/UK010326,7 March 12pm GMT 2026,https://www.phillips.com/detail/yu-nishimura/2...,231482.0,Yu Nishimura,On the Table,"£20,000 - £30,000",38700.0,£,...,GBP,2026-03-07,2026-03-07,2026,3,5.139619e+04,5.139619e+04,1.328067,2.656134e+04,3.984201e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24812,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-sérusier/...,193320.0,Paul Sérusier,La Cueillette des pommes,"$1,500,000 - $2,000,000",1391000.0,$,...,USD,2023-11-14,2023-11-14,2023,11,1.391000e+06,1.542227e+06,1.000000,1.663077e+06,2.217436e+06
24813,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/félix-vallotto...,193324.0,Félix Vallotton,Papotage,"$300,000 - $500,000",330200.0,$,...,USD,2023-11-14,2023-11-14,2023,11,3.302000e+05,3.660986e+05,1.000000,3.326154e+05,5.543589e+05
24814,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/paul-gauguin/1...,193312.0,Paul Gauguin,Masque de Meyer de Haan,"$60,000 - $80,000",66040.0,$,...,USD,2023-11-14,2023-11-14,2023,11,6.604000e+04,7.321973e+04,1.000000,6.652307e+04,8.869743e+04
24815,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/robert-ryman/1...,193335.0,Robert Ryman,"Untitled, Prototype","$300,000 - $500,000",254000.0,$,...,USD,2023-11-14,2023-11-14,2023,11,2.540000e+05,2.816143e+05,1.000000,3.326154e+05,5.543589e+05
24816,LIVING THE AVANT-GARDE: THE TRITON COLLECTION ...,https://www.phillips.com/auction/NY011123,14 November 6pm ET 2023,https://www.phillips.com/detail/sam-francis/19...,193329.0,Sam Francis,"Purple, Orange & Green","$200,000 - $300,000",482600.0,$,...,USD,2023-11-14,2023-11-14,2023,11,4.826000e+05,5.350672e+05,1.000000,2.217436e+05,3.326154e+05

In [36]:
output_file = 'phillips_cleaned.csv'
df_cleaned.to_csv(output_file, index=False, encoding='utf-8-sig')